<?php
return array(
	'BE' => array(
		'adminOnly' => '0',
		'disable_exec_function' => 0,
		'explicitADmode' => 'explicitAllow',
		'fileCreateMask' => '0666',
		'folderCreateMask' => '2777',
		'installToolPassword' => '6173b783e4c6eb306eb4715d3ccd8d9a',
		'versionNumberInFilename' => '0',
	),
	'DB' => array(
		'database' => 'DB1712798',
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => 'rdbms.strato.de',
		'password' => 'lS4YXD7pC5EhgIas4',
		'username' => 'U1712798',
	),
	'EXT' => array(
		'extConf' => array(
			'automaketemplate' => 'a:0:{}',
			'cal' => 'a:22:{s:13:"noTabDividers";s:1:"0";s:21:"hideLocationTextfield";s:1:"0";s:22:"hideOrganizerTextfield";s:1:"0";s:20:"useLocationStructure";s:15:"tx_cal_location";s:21:"useOrganizerStructure";s:16:"tx_cal_organizer";s:11:"todoSubtype";s:5:"event";s:16:"categoryTVHeight";s:3:"280";s:11:"treeOrderBy";s:3:"uid";s:9:"showTimes";s:1:"1";s:10:"newRecurUI";s:1:"1";s:9:"useTeaser";s:1:"0";s:17:"useRecordSelector";s:1:"0";s:20:"useNewRecurringModel";s:1:"1";s:20:"hideDeviationRecords";s:1:"1";s:15:"recurrenceStart";s:8:"20000101";s:13:"recurrenceEnd";s:8:"20201231";s:13:"updateMessage";s:1:"0";s:18:"useInternalCaching";s:1:"1";s:11:"cachingMode";s:6:"normal";s:13:"cacheLifetime";s:1:"0";s:13:"cachingEngine";s:8:"internal";s:30:"enableRealURLAutoConfiguration";s:1:"1";}',
			'convert2utf8' => 'a:0:{}',
			'converter2utf8' => 'a:5:{s:13:"tablesExclude";s:0:"";s:15:"tablesProcessed";s:0:"";s:12:"enableDevlog";s:1:"1";s:13:"updateMessage";s:1:"0";s:8:"__meta__";N;}',
			'feedit' => 'a:0:{}',
			'indexed_search' => 'a:18:{s:8:"pdftools";s:9:"/usr/bin/";s:8:"pdf_mode";s:2:"20";s:5:"unzip";s:9:"/usr/bin/";s:6:"catdoc";s:9:"/usr/bin/";s:6:"xlhtml";s:9:"/usr/bin/";s:7:"ppthtml";s:9:"/usr/bin/";s:5:"unrtf";s:9:"/usr/bin/";s:9:"debugMode";s:1:"0";s:18:"fullTextDataLength";s:1:"0";s:23:"disableFrontendIndexing";s:1:"0";s:21:"enableMetaphoneSearch";s:1:"1";s:6:"minAge";s:2:"24";s:6:"maxAge";s:1:"0";s:16:"maxExternalFiles";s:1:"5";s:26:"useCrawlerForExternalFiles";s:1:"0";s:11:"flagBitMask";s:3:"192";s:16:"ignoreExtensions";s:0:"";s:17:"indexExternalURLs";s:1:"0";}',
			'info' => 'a:0:{}',
			'jquerycolorbox' => 'a:0:{}',
			'linkvalidator' => 'a:0:{}',
			'news' => 'a:11:{s:29:"removeListActionFromFlexforms";s:1:"0";s:20:"pageModuleFieldsNews";s:313:"LLL:EXT:news/Resources/Private/Language/locallang_be.xml:pagemodule_simple=title,datetime;LLL:EXT:news/Resources/Private/Language/locallang_be.xml:pagemodule_advanced=title,datetime,teaser,category;LLL:EXT:news/Resources/Private/Language/locallang_be.xml:pagemodule_complex=title,datetime,teaser,category,archive;";s:24:"pageModuleFieldsCategory";s:17:"title,description";s:6:"tagPid";s:1:"1";s:13:"prependAtCopy";s:1:"1";s:19:"categoryRestriction";s:4:"none";s:22:"contentElementRelation";s:1:"0";s:13:"manualSorting";s:1:"0";s:11:"archiveDate";s:4:"date";s:12:"showImporter";s:1:"0";s:24:"showAdministrationModule";s:1:"1";}',
			'opendocs' => 'a:0:{}',
			'realurl' => 'a:5:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"1";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
			'recycler' => 'a:0:{}',
			'rlmp_tmplselector' => 'a:1:{s:12:"templateMode";s:4:"file";}',
			'rtehtmlarea' => 'a:13:{s:21:"noSpellCheckLanguages";s:23:"ja,km,ko,lo,th,zh,b5,gb";s:15:"AspellDirectory";s:15:"/usr/bin/aspell";s:17:"defaultDictionary";s:2:"en";s:14:"dictionaryList";s:2:"en";s:20:"defaultConfiguration";s:105:"Typical (Most commonly used features are enabled. Select this option if you are unsure which one to use.)";s:12:"enableImages";s:1:"1";s:20:"enableInlineElements";s:1:"0";s:19:"allowStyleAttribute";s:1:"1";s:24:"enableAccessibilityIcons";s:1:"0";s:16:"enableDAMBrowser";s:1:"0";s:16:"forceCommandMode";s:1:"0";s:15:"enableDebugMode";s:1:"0";s:23:"enableCompressedScripts";s:1:"1";}',
			'scheduler' => 'a:4:{s:11:"maxLifetime";s:4:"1440";s:11:"enableBELog";s:1:"1";s:15:"showSampleTasks";s:1:"1";s:11:"useAtdaemon";s:1:"0";}',
			'simulatestatic' => 'a:0:{}',
			'workspaces' => 'a:0:{}',
			'wt_spamshield' => 'a:10:{s:12:"useNameCheck";s:1:"0";s:12:"usehttpCheck";s:1:"3";s:9:"notUnique";s:0:"";s:13:"honeypodCheck";s:1:"1";s:15:"useSessionCheck";s:1:"1";s:16:"SessionStartTime";s:2:"10";s:14:"SessionEndTime";s:3:"600";s:10:"AkismetKey";s:0:"";s:12:"email_notify";s:0:"";s:3:"pid";s:2:"-1";}',
		),
		'extListArray' => array(
			'introduction',
			'perm',
			'func',
			'filelist',
			'about',
			'version',
			'tsconfig_help',
			'context_help',
			'extra_page_cm_options',
			'impexp',
			'sys_note',
			'tstemplate',
			'tstemplate_ceditor',
			'tstemplate_info',
			'tstemplate_objbrowser',
			'tstemplate_analyzer',
			'func_wizards',
			'wizard_crpages',
			'wizard_sortpages',
			'lowlevel',
			'install',
			'belog',
			'beuser',
			'aboutmodules',
			'setup',
			'taskcenter',
			'info_pagetsconfig',
			'viewpage',
			'rtehtmlarea',
			'css_styled_content',
			't3skin',
			't3editor',
			'reports',
			'felogin',
			'form',
			'workspaces',
			'scheduler',
			'linkvalidator',
			'automaketemplate',
			'news',
			'indexed_search',
			'wt_spamshield',
			'jquerycolorbox',
			'info',
			'feedit',
			'opendocs',
			'recycler',
			'rlmp_tmplselector',
			'converter2utf8',
			'cal',
		),
	),
	'EXTCONF' => array(
		'lang' => array(
			'availableLanguages' => array(
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'de',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
			),
		),
	),
	'FE' => array(
		'pageNotFound_handling' => 'http://www.r-s-schule.de/index.php?id=16',
	),
	'GFX' => array(
		'gdlib_png' => 1,
		'im' => 0,
		'im_combine_filename' => '',
		'im_imvMaskState' => 1,
		'im_negate_mask' => 0,
		'im_path' => '',
		'im_path_lzw' => '',
		'jpg_quality' => '80',
	),
	'INSTALL' => array(
		'wizardDone' => array(
			'TYPO3\CMS\Install\CoreUpdates\InstallSysExtsUpdate' => '["info","perm","func","filelist","about","cshmanual","feedit","opendocs","recycler","t3editor","reports","scheduler","simulatestatic"]',
			'TYPO3\CMS\Install\Updates\FilemountUpdateWizard' => 1,
			'TYPO3\CMS\Install\Updates\TceformsUpdateWizard' => 'tt_content:image,pages:media,pages_language_overlay:media',
		),
	),
	'SYS' => array(
		'compat_version' => '6.1',
		'encryptionKey' => 'n(x^pwUgAL*rNHLndea2LFGFOBi7L*(Xxv16Ufvrx4seE@#^W3kESP7vU)dEDB&p',
		'sitename' => 'rsschule',
	),
);
?>